language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - rvm reinstall ruby-head --binary
  - bundle install --path vendor/cache
  - npm install -g firebase-tools
  - npm install ruby
  - npm install -g gulp
  - which -a ruby
  - gem install jekyll

script:
  - jekyll build

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}