language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g jekyll

script:
  - jekyll serve

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}